aliyo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from home.sitemaps import StaticHomeViewSitemap
from contact.sitemaps import StaticContactViewSitemap
from pricing.sitemaps import StaticPricingViewSitemap
from solutions.sitemaps import StaticSolutionsViewSitemap

sitemaps = {
    'staticHome' : StaticHomeViewSitemap,
    'staticSolutions' : StaticSolutionsViewSitemap,
    'staticContact' : StaticContactViewSitemap,
    'staticPricing' : StaticPricingViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'))),
    path('', include(('contact.urls', 'home'))),
    path('', include(('solutions.urls', 'home'))),
    path('', include(('pricing.urls', 'home'))),
    path('sitemap.xml', sitemap, {'sitemaps' : sitemaps}),
]

handler404 = 'home.views.error_404_view'

contact/urls.py
from django.urls import path

from contact import views

app_name = "contact"
urlpatterns = [
    path("contact/", views.Contact.as_view(), name="contact"),
    path("a-propos/", views.About.as_view(), name="about"),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("mentions-legales/", views.LegalNotice.as_view(), name="legalNotice"),
    path("politique-de-confidentialite/", views.PrivacyPolicy.as_view(), name="privacyPolicy"),
]

pricing/urls.py
from django.urls import path

from pricing import views

app_name = "pricing"
urlpatterns = [
    path("tarifs/", views.Pricing.as_view(), name="pricing"),
]

solutions/urls.py
from django.urls import path

from solutions import views

app_name = "solutions"
urlpatterns = [
    path("creer-un-site-web/", views.WebSite.as_view(), name="website"),
    path("creer-une-application-mobile/", views.MobileApp.as_view(), name="mobileApp"),
]

pricing/models.py
from django.db import models

# Create your models here.

solutions/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField(max_length = 512)
    message = forms.CharField()

contact/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings
from django.contrib import messages

from contact.forms import ContactForm
from contact.sender import Sender

class Contact(View):
    def get(self, request):
        context = {}
        context["site_key"] = settings.RECAPTCHA_SITE_KEY
        return render(request, "contact.html", context)

    def post(self, request):
        data = request.POST
        contact_form = ContactForm(data)
        if contact_form.is_valid():
            sender = Sender(contact_form)
            if sender.is_recaptach_sucess(data):
                sender.send_message_to_customer()
                sender.send_message_to_manager()
                messages.success(request, 'Merci pour votre message, nous allons y répondre au plus vite !')

        context = {}
        context["site_key"] = settings.RECAPTCHA_SITE_KEY
        return render(request, "contact.html", context)

class About(View):
    def get(self, request):
        context = {}
        return render(request, "about.html", context)

home/views.py
from django.shortcuts import render
from django.views import View

class Home(View):
    def get(self, request):
        context = {}
        return render(request, "home.html", context)

class LegalNotice(View):
    def get(self, request):
        context = {}
        return render(request, "legalNotice.html", context)

class PrivacyPolicy(View):
    def get(self, request):
        context = {}
        return render(request, "privacyPolicy.html", context)

def error_404_view(request, exception):
    return render(request, '404.html')

pricing/views.py
from django.shortcuts import render
from django.views import View

class Pricing(View):
    def get(self, request):
        context = {}
        return render(request, "pricing.html", context)

solutions/views.py
from django.shortcuts import render
from django.views import View

class WebSite(View):
    def get(self, request):
        context = {}
        return render(request, "website.html", context)


class MobileApp(View):
    def get(self, request):
        context = {}
        return render(request, "mobileApp.html", context)

contact/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}À propos de nous - ALIYO | Spécialistes de la création de sites web et d'applications mobiles{% endblock title %}
{% block description %}Découvrez notre équipe d'experts passionnés et notre approche personnalisée de la création de sites web et d'applications mobiles. Chez ALIYO, nous sommes déterminés à fournir les meilleures solutions numériques pour vous aider à réussir en ligne.{% endblock description %}

{% block content %}
<header class="page-header-ui page-header-ui-dark bg-gradient-primary-to-secondary">
    <div class="page-header-ui-content pt-10">
        <div class="container px-5 text-center">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8">
                    <h1 class="page-header-ui-title mb-3">À propos de nous !</h1>
                    <p class="page-header-ui-text">Découvrez qui nous sommes et comment nous pouvons vous aider à réussir en ligne</p>
                </div>
            </div>
        </div>
    </div>
    <div class="svg-border-rounded text-white">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none" fill="currentColor"><path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path></svg>
    </div>
</header>
<section class="bg-white">
	<div class="container pt-5">
		<div class="row align-items-md-center mb-5">
			<div class="col-md-12">
				<div class="lc-block text-center">
					<h2 editable="inline" class="display-5 mb-0"><b>La créativité au service de votre entreprise</b></h2>
					<p editable="inline"> Nous sommes là pour vous aider à transformer votre entreprise en ligne.<br>Découvrez comment !</p>
				</div>
			</div>
		</div>
		<div class="row align-items-md-center mb-5">
			<div class="col-md-6 pr-5" data-aos="fade-right">
				<div class="lc-block py-2">
					<span class="badge bg-dark" editable="inline">QUI SOMMES NOUS ?</span>
				</div>
				<div class="lc-block mb-4">
					<h2 editable="inline">Notre passion, votre réussite.</h2>
				</div>
				<div class="lc-block text-muted">
					<div editable="rich">
						<p> Nous sommes une entreprise spécialisée dans le développement web, les applications mobiles et la mise en ligne de votre entreprise. Nous visons à fournir à nos clients les meilleures solutions disponibles sur le marché à un prix raisonnable et abordable. Nous sommes déterminés à les accompagner dans leur transformation numérique en les aidant à tout faire en un seul endroit.</p><br/>
						<p>Nous avons réuni des professionnels expérimentés qui ont déjà fait leurs preuves dans leur domaine respectif, afin d'offrir des solutions innovantes à nos clients. Chez nous, nous croyons en la puissance du travail d'équipe et de la collaboration pour fournir les meilleurs services possibles à nos clients.</p>
						<p>Nous sommes heureux de pouvoir aider toute entreprise qui souhaite faire un pas en avant dans son développement grâce à ALIYO. Nous croyons en notre capacité à offrir des solutions sur mesure et efficaces pour soutenir les entreprises dans leur transformation numérique.</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="lc-block">
					<div class="card shadow-sm border-light" data-aos="fade-down">
						<img src="{% static 'assets/img/about/srilanka2.jpg' %}" alt="Featured image 1" class="card-img-top" loading="lazy">
					</div>
				</div>
				<div class="lc-block">
					<div class="card shadow-sm border-light mt-4" data-aos="fade-up">
						<img src="{% static 'assets/img/about/srilanka1.jpg' %}" alt="Featured image 2" class="card-img-top" loading="lazy">
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 pl-sm-3 mt-3 mt-sm-0">
				<div class="lc-block">
					<div class="card shadow-sm border-light" data-aos="fade-left">
						<img src="{% static 'assets/img/about/srilanka3.jpg' %}" alt="Featured image 3" class="card-img-top" loading="lazy">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

contact/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}Contactez-nous pour toutes vos questions et projets digitaux | ALIYO{% endblock title %}
{% block description %}Contactez-nous pour toutes vos questions et projets digitaux. Notre équipe expérimentée est là pour vous aider à amener votre entreprise en ligne avec des solutions personnalisées. Remplissez notre formulaire de contact pour commencer dès maintenant.{% endblock description %}

{% block content %}
<header class="page-header-ui page-header-light py-lg-5 bg-gradient-primary-to-secondary">
    <div class="page-header-ui-content mt-10">
        <div class="container px-5">
            <div class="text-center mb-5" data-aos="zoom-in">
                <h1 class="section-heading text-uppercase text-white">Contactez-Nous</h1>
                <h2 class="section-subheading text-muted">Posez-nous toutes vos questions, on vous répond !</h2>
            </div>
            <div class="row gx-5 align-items-center">
                <div class="col-lg-4 d-none d-lg-block" data-aos="zoom-in"><img class="img-fluid" src="{% static 'assets/img/logos/Aliyo_logo_White.png' %}" /></div>
                <div class="col-lg-8">
                    {% if messages %}
                        {% for message in messages %}
                            <p class="text-white" data-aos="zoom-in"><strong>{{ message }}</strong></p>
                        {% endfor %}
                    {% else %}
                    <form id="contactForm" action="{% url 'contact:contact' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="g-recaptcha-response" id='recaptcha'>
                    <div class="row align-items-stretch mb-5">
                        <div class="col-md-6" data-aos="fade-right">
                            <div class="form-group">
                                <input class="form-control" id="name" type="text" placeholder="Votre Nom *" name="name" required/>
                            </div>
                        </div>
                        <div class="col-md-6" data-aos="fade-left">
                            <div class="form-group">
                                <input class="form-control" id="email" type="email" placeholder="Votre Email *" name="email" required/>
                            </div>
                        </div>   
                    </div>
                    <div class="row align-items-stretch mb-5" data-aos="fade-up">
                        <div class="form-group form-group-textarea">
                            <textarea class="form-control" id="message" placeholder="Votre message *" name="message" required></textarea>
                        </div>
                    </div>
                    <div class="text-center" data-aos="fade-up"><button class="btn btn-primary btn-xl text-uppercase" id="submitButton" type="submit">Envoyer</button></div>
                </form>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="svg-border-rounded text-light">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none" fill="currentColor"><path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path></svg>
    </div>
</header>
{% endblock %}

home/templates/legalNotice.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% endblock title %}

{% block description %}{% endblock description %}

{% block content %}
<header class="page-header-ui page-header-ui-dark bg-gradient-primary-to-secondary">
    <div class="page-header-ui-content pt-10">
        <div class="container px-5 text-center">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8">
                    <h1 class="page-header-ui-title mb-3">Mentions légales</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="svg-border-rounded text-white">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none" fill="currentColor"><path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path></svg>
    </div>
</header>
<section class="bg-white py-10">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-10 mt-5">
                <h1>Mentions légales</h1>
                <!--<p class="lead">Last updated: January 2020</p>-->
                <hr class="my-5" />
                <h2 class="mb-3">1. Edition du site</h2>
                <p>Le présent site, accessible à l’URL www.aliyo.fr (le « Site »), est édité par :</p>
                <p>ALIYO, société au capital de 1500 euros, inscrite au R.C.S. de NANTERRE sous le numéro Nanterre B 950 785 782, dont le siège social est situé au 25 RUE DU 19 JANVIER 92380 GARCHES, représenté par Ranga Gonnage & Dylan Francisku dûment habilités</p>
                <p>Le numéro individuel TVA de l’éditeur est : FR93950785782.</p>
                <hr class="my-5" />
                <h2 class="mb-3">2. Hébergement</h2>
                <p>Le Site est hébergé par la société Heroku, situé The Landmark at One Market, Suite 300, San Francisco, CA 94105, United States, (contact téléphonique ou email : +18662781349).</p>
                <hr class="my-5" />
                <h2 class="mb-3">3. Directeur de publication</h2>
                <p>Le Directeur de la publication du Site est Ranga Gonnage .</p>
                <hr class="my-5" />
                <h2 class="mb-3">4. Nous contacter</h2>
                <p>Par téléphone : +33607895009</p>
                <p>Par email : contact@aliyo.fr</p>
                <p>Par courrier : 25 RUE DU 19 JANVIER 92380 GARCHES</p>
                <hr class="my-5" />
                <div class="card z-1 mb-n10">
                    <div class="card-body text-center py-5">
                        <h2 class="mb-3">Nous sommes là pour vous aider ! </h2>
                        <a class="btn btn-primary fw-500" href="{% url 'contact:contact'%}">Contactez-nous !</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="svg-border-rounded text-light">
        <!-- Rounded SVG Border-->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none" fill="currentColor"><path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path></svg>
    </div>
</section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="{% block description %}Créez votre site web professionnel facilement avec ALIYO. Notre solution de création de site web offre un accompagnement personnalisé et des fonctionnalités sur mesure. Découvrez nos offres dès maintenant.{% endblock description %}"/>
        <meta name="author" content="Aliyo" />
        <title>{% block title %}Créez votre site web professionnel avec notre solution de création sur mesure - ALIYO{% endblock title %}</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logos/Aliyo_logo_Black.png' %}" />
        <script data-search-pseudo-elements defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.24.1/feather.min.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
        <!--Google Recaptcha-->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>

        <script src="https://www.google.com/recaptcha/api.js?render={{ site_key }}"></script>
        <script>
          grecaptcha.ready(function() {
              $('#contactForm').submit(function(e){
                  var form = this;
                  e.preventDefault()
                  grecaptcha.execute('{{ site_key }}', {action: 'contactform'}).then(function(token) {
                      $('#recaptcha').val(token)
                      form.submit()
                  });
              })

          });
        </script>
        <!--Google Recaptcha END-->
    </head>
    <body>
        <div id="layoutDefault">
            <div id="layoutDefault_content">
                <main>
                    <nav class="navbar navbar-marketing navbar-expand-lg bg-transparent navbar-dark fixed-top">
                        <div class="container px-5">
                            <a class="navbar-brand" href="{% url 'home:home'%}"><img class="img-responsive" src="{% static 'assets/img/logos/Aliyo_full_logo_white.png' %}" width="140px" height="70px" alt="Logo Aliyo"/></a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i data-feather="menu"></i></button>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ms-auto me-lg-5">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'home:home'%}">Accueil</a></li>
                                    <li class="nav-item dropdown dropdown-xl no-caret">
                                        <a class="nav-link dropdown-toggle" id="navbarDropdownPages" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Solutions
                                            <i class="fas fa-chevron-right dropdown-arrow"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end me-lg-n20 me-xl-n15 animated--fade-in-up" aria-labelledby="navbarDropdownPages">
                                            <div class="row g-0">
                                                <!--<div class="col-lg-4 p-lg-5">-->
                                                <div class="col-lg-6 p-lg-4">
                                                    <h6 class="dropdown-header text-primary"><a href="{% url 'solutions:website'%}">Site web</a></h6>
                                                    <a class="dropdown-item" href="{% url 'solutions:website'%}">Création de Site Web</a>
                                                    <div class="dropdown-divider border-0"></div>
                                                    <!--<h6 class="dropdown-header text-primary"><a href="{% url 'solutions:mobileApp'%}">Application mobile</a></h6>
                                                    <a class="dropdown-item" href="{% url 'solutions:mobileApp'%}">Création d'application mobile</a>
                                                    <div class="dropdown-divider border-0"></div>-->
                                                    <!--<h6 class="dropdown-header text-primary">Transformation digitale</h6>
                                                    <a class="dropdown-item" href="page-help-center.html">Intelligence artificielle</a>
                                                    <a class="dropdown-item" href="page-help-center.html">Robots RPA</a>
                                                    <a class="dropdown-item" href="page-help-center.html">Services cloud</a>
                                                    <div class="dropdown-divider border-0"></div>-->
                                                </div>
                                                <!--<div class="col-lg-4 p-lg-5">-->
                                                <div class="col-lg-6 p-lg-4">
                                                    <h6 class="dropdown-header text-primary"><a href="{% url 'solutions:mobileApp'%}">Application mobile</a></h6>
                                                    <a class="dropdown-item" href="{% url 'solutions:mobileApp'%}">Création d'application mobile</a>
                                                    <div class="dropdown-divider border-0"></div>
                                                    <!--<h6 class="dropdown-header text-primary">Création de contenu</h6>
                                                    <a class="dropdown-item" href="page-careers-overview.html">Création de logo</a>
                                                    <a class="dropdown-item" href="page-careers-listing.html">UX design</a>
                                                    <a class="dropdown-item" href="page-careers-listing.html">Rédaction de contenu</a>
                                                    <a class="dropdown-item" href="page-careers-listing.html">Photo & Vidéo professionnelle</a>
                                                    <a class="dropdown-item" href="page-careers-listing.html">Développement de marque</a>
                                                    <a class="dropdown-item" href="page-careers-listing.html">Infographie</a>
                                                    <div class="dropdown-divider border-0"></div>
                                                </div>-->
                                                <!--<div class="col-lg-4 p-lg-5">
                                                    <h6 class="dropdown-header text-primary">Marketing digital</h6>
                                                    <a class="dropdown-item" href="page-error-400.html">Services SEO</a>
                                                    <a class="dropdown-item" href="page-error-401.html">Campagne publicitaire</a>
                                                    <a class="dropdown-item" href="page-error-404-1.html">Campagne d'emailing</a>
                                                </div>-->
                                            </div>
                                        </div>
                                    </li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'pricing:pricing'%}">Tarifs</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'contact:about'%}">À propos</a></li>
                                </ul>
                                <a class="btn fw-500 ms-lg-4 btn-teal" href="{% url 'contact:contact'%}">
                                    Contactez-nous !
                                    <i class="ms-2" data-feather="arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </nav>
                    <hr class="m-0" />
                    {% block content %}{% endblock %}
                </main>
            </div>       
            <div id="layoutDefault_footer">
                <footer class="footer pt-5 mt-auto bg-light footer-light">
                    <div class="container px-5">
                        <div class="row gx-5">
                            <div class="col-lg-3">
                                <a class="navbar-brand" href="{% url 'home:home'%}"><img class="img-responsive" src="{% static 'assets/img/logos/Aliyo_full_logo_black.png' %}" width="100px" height="50px" alt="Logo Aliyo"/></a>
                                <div class="icon-list-social mb-5">
                                    <a class="icon-list-social-link" href="https://www.linkedin.com/company/aliyo/" target="_blank"><i class="fab fa-linkedin"></i></a>
                                    <!--<a class="icon-list-social-link" href="#!"><i class="fab fa-instagram"></i></a>-->
                                    <a class="icon-list-social-link" href="https://www.facebook.com/profile.php?id=100090741787608" target="_blank"><i class="fab fa-facebook"></i></a>
                                </div>
                            </div>
                            <div class="col-lg-9">
                                <div class="row gx-5">
                                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                                    </div>
                                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                                        <div class="text-uppercase-expanded text-xs mb-4">Plan de site</div>
                                        <ul class="list-unstyled mb-0">
                                            <li class="mb-2"><a href="{% url 'home:home'%}">Accueil</a></li>
                                            <li class="mb-2"><a href="{% url 'solutions:website'%}">Créer un site</a></li>
                                            <li class="mb-2"><a href="{% url 'solutions:mobileApp'%}">Créer une application</a></li>
                                            <li class="mb-2"><a href="{% url 'pricing:pricing'%}">Tarifs</a></li>
                                            <li><a href="{% url 'contact:about'%}">À propos</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                                        <div class="text-uppercase-expanded text-xs mb-4">Entreprise</div>
                                        <ul class="list-unstyled mb-0">
                                            <li class="mb-2"><a href="{% url 'contact:about'%}">À propos</a></li>
                                            <li><a href="{% url 'contact:contact'%}">Contact</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-3 col-md-6">
                                        <div class="text-uppercase-expanded text-xs mb-4">Juridique</div>
                                        <ul class="list-unstyled mb-0">
                                            <li class="mb-2"><a href="{% url 'home:legalNotice'%}">Mentions légales</a></li>
                                            <li><a href="{% url 'home:privacyPolicy'%}">Politique de confidentialité</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-3" />
                        <div class="row pb-3 gx-5 align-items-center">
                            <div class="col-md-6 small">Copyright &copy; Aliyo 2023</div>
                            <div class="col-md-6 text-md-end small">
                                <a href="{% url 'home:legalNotice'%}">Mentions légales</a>
                                &middot;
                                <a href="{% url 'home:privacyPolicy'%}">Politique de confidentialité</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
            AOS.init({
                disable: 'mobile',
                duration: 400,
                once: true,
            });
        </script>
    </body>
</html>